version: '3.8'

services:
  jusc-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jusc_web
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      # Persistência do banco de dados na VPS
      - ./data:/app/data
      # Persistência das fotos e uploads na VPS
      - ./uploads:/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jusc.rule=Host(`jusc.tccodes.com.br`)"
      - "traefik.http.routers.jusc.entrypoints=websecure"
      - "traefik.http.routers.jusc.tls.certresolver=myresolver"
      - "traefik.http.services.jusc.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
